Galo_Personal_Site/Controllers/JavaScriptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Galo_Personal_Site.Controllers
{
    [RequireHttps]
    public class JavaScriptController : Controller
    {
        // GET: JavaScript
        public ActionResult Exeuno()
        {
            return View();
        }

        public ActionResult Exedos()
        {
            return View();
        }

        public ActionResult Exetres()
        {
            return View();
        }

        public ActionResult Execuatro()
        {
            return View();
        }

        public ActionResult Execinco()
        {
            return View();
        }

        public ActionResult JSProblems()
        {
            return View();
        }
    }

}

Galo_Personal_Site/Views/JavaScript/Execuatro.cshtml
<div class="container-fluid">
    <button type="button" data-toggle="modal" data-target="#max" class="btn">Show Code</button>
</div>    

<div class="container">
        <div class="row"><br />  
        </div>
        <div class="row">
            <div class="col-xs-4">
                <h1>PROBLEM 4</h1>
            </div>
        <div class="row"><br />
            <div class="col-xs-12">
                <form>
                    The following program determines if the word is a palindrome:
                    <input type="text" id="temp">
                    <input type="button" onclick="palindrome()" value="Submit">
                </form>
            </div>            
        </div>

        <div class="row"><br />
            <div class="col-xs-12" id="temp1"></div>
        </div>

        <div class="modal fade" tabindex="-1" id="max" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h1 class="modal-title" id="myModalLabel">Code for Problem 4</h1>
                    </div>

                    <div class="modal-body">
                        <pre class="brush: js; gutter: false; toolbar: false;">
    function palindrome() {
        var original = document.getElementById("temp").value;
        var reverse = "";
        var length = original.length;
        for (var i = length - 1; i >= 0; i--)
            reverse = reverse + original.charAt(i);
        if (original === reverse)
            window.alert("The entered word is a palindrome");
        else
            window.alert("The entered word is not a palindrome");
    }
</pre>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section scripts{
    <script>
    function palindrome() {
        var original = document.getElementById("temp").value;
        var reverse = "";
        var length = original.length;

        for (var i = length - 1; i >= 0; i--)
            reverse = reverse + original.charAt(i);

        if (original === reverse)
            temp1.innerHTML = "The entered word is a palindrome";
        else
            temp1.innerHTML = "The entered word is not a palindrome";
    }
    </script>}
</div>

Galo_Personal_Site/Views/JavaScript/Exedos.cshtml
<div class="container-fluid">
    <button type="button" data-toggle="modal" data-target="#max" class="btn">Show Code</button>
</div>
    
<div class="container">
        <div class="row"><br /></div>
        <div class="row">
            <div class="col-xs-4">
                <h1>PROBLEM 2</h1>
            </div>
        </div>
        <div class="row"><br />
            <div class="col-xs-12">
                <form>
                    Input a number to obtain its factorial:
                    <input type="number" id="temp" min="1" max="Infinity">
                    <button type="button" onclick="factorial()">Submit</button>
                </form>
            </div>
        </div>

        <div class="row"><br />
            <div class="col-xs-12">
                <div id="temp1"></div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" id="max" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h1 class="modal-title" id="myModalLabel">Code for Problem 2</h1>
                    </div>

                    <div class="modal-body">
                        <pre class="brush: js; gutter: false; toolbar: false;">
    function factorial() {
		var y = document.getElementById("temp").value;
		var x = y;
		var result = 1;
		while(x > 1) {
			result *= x;
			x--;
		}
		window.alert("The factorial of " + y + " is: " + result);
	}
</pre>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section scripts{
	<script>
	function factorial() {
		var y = document.getElementById("temp").value;
		var x = y;
		var result = 1;

		while(x > 1) {
			result *= x;
			x--;
		}
		temp1.innerHTML = "The factorial of " + y + " is: " + result;
	}
	</script>}

Galo_Personal_Site/Views/JavaScript/Exetres.cshtml
<div class="container-fluid">
    <button type="button" data-toggle="modal" data-target="#max" class="btn">Show Code</button>
</div>
   
 <div class="container">
        <div class="row"><br /></div>
        <div class="row">
            <div class="col-xs-4">
                <h1>PROBLEM 3</h1>
            </div>
        </div>
        <div class="row"><br />
            <p>
                The following program accepts two numbers between 1 & 100. Then iterates form 1 to 100 and prints them in ascending order. 
                <li>For each number that is a multiple of the first number, the program prints: <b>Fizz</b></li>
                <li>For each number that is a multiple of the seond number, the program prints: <b>Buzz</b></li>                    
                <li>For eahc number that is a multiple of both, the program prints: <b>FizzBuzz</b></li>
            </p>
        </div>
        <div class="row"><br />
                <form>
                    Input the first number: <input type="number" id="uno" min="1" max="100">
                    Input the second number: <input type="number" id="dos" min="1 max='100">
                    <button type="button" onclick="iteration()">Go!</button>
                </form><br />
        </div>
        <div class="row">
            <div class="col-xs-10">
                <div id="numbers"></div>
            </div>
        </div>

        <div class="modal fade" tabindex="-1" id="max" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h1 class="modal-title" id="myModalLabel">Code for Problem 3</h1>
                    </div>

                    <div class="modal-body">
                        <pre class="brush: js; gutter: false; toolbar: false;">
  	function iteration() {
		var a = document.getElementById("uno").value;
		var b = document.getElementById("dos").value;
		var num = document.getElementById("numbers");
		num.innerHTML = "";
		for(var i=1; i <= 100; i++) {
			if(((i % a) == 0)&&((i %b) == 0))
				num.innerHTML += ('FizzBuzz') + "<br />";
			else if((i % a) == 0)
				num.innerHTML += ('Fizz') + "<br />";
			else if((i % b) == 0)
				num.innerHTML += ('Buzz') + "<br />";
			else
				num.innerHTML += (i) + "<br />";
		}
	}

</pre>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
	
    @section scripts{
	<script>
	function iteration() {
		var a = document.getElementById("uno").value;
		var b = document.getElementById("dos").value;
		var num = document.getElementById("numbers");
		num.innerHTML = "";

		for(var i=1; i <= 100; i++) {
			if(((i % a) == 0)&&((i %b) == 0))
				num.innerHTML += ('FizzBuzz') + "<br />";
			else if((i % a) == 0)
				num.innerHTML += ('Fizz') + "<br />";
			else if((i % b) == 0)
				num.innerHTML += ('Buzz') + "<br />";
			else
				num.innerHTML += (i) + "<br />";
		}
	}
	</script>}

Galo_Personal_Site/Views/JavaScript/Exeuno.cshtml
<div class="container-fluid">
    <button type="button" data-toggle="modal" data-target="#max" class="btn">Show Code</button>
</div>

<div class="container"> 
    <div class="row">
        <h2>PROBLEM 1</h2>
        <p>The following program accepts a series of at least 5 numbers and performs the following operations:</p>            
    </div>
    <div class="row">
        <div class="col-sm-4">
            <form>
                Input a number: <input class="form-control" type="number" id="first"><br>
                Input a number: <input class="form-control" type="number" id="second"><br>
                Input a number: <input class="form-control" type="number" id="third"><br>
                Input a number: <input class="form-control" type="number" id="fourth"><br>
                Input a number: <input class="form-control" type="number" id="fifth"><br><br>
            </form>
        </div>
        <div class="col-sm-2">
            <div class="btn btn-group-vertical" role="group">
                <button onclick="min()" class="btn btn-primary">LEAST</button>
                <button onclick="max()" class="btn btn-primary">GREATEST</button>
                <button onclick="mean()" class="btn btn-primary">MEAN</button>
                <button onclick="add()" class="btn btn-primary">SUM</button>
                <button onclick="mult()" class="btn btn-primary">MEAN</button>
            </div>
        </div>
        <div class="col-sm-1">
            <div id="temp1" style="padding-top: 10px; padding-bottom: 12px"></div>
            <div id="temp2" style="padding-bottom: 12px"></div>
            <div id="temp3" style="padding-bottom: 12px"></div>
            <div id="temp4" style="padding-bottom: 12px"></div>
            <div id="temp5" style="padding-bottom: 10px"></div>
        </div>
    </div>
    @*<div class="container">
        <div class="row">
            <div class="col-md-2">
                <a onclick="min()" class="btn btn-primary">LEAST</a>
            </div>
            <div class="col-sm-2">
                <div id="temp1"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <a onclick="max()" class="btn btn-primary">GREATEST</a>
            </div>
            <div class="col-md-2">
                <div id="temp2"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <a onclick="mean()" class="btn btn-primary">MEAN</a>
            </div>
            <div class="col-md-2">
                <div id="temp3"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <a onclick="add()" class="btn btn-primary">SUM</a>
            </div>
            <div class="col-md-2">
                <div id="temp4"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <a onclick="mult()" class="btn btn-primary">MEAN</a>
            </div>
            <div class="col-md-2">
                <div id="temp5"></div>
            </div>
        </div>
        <div class="row"><br />
            <form>
                Input a number: <input class="form-control" type="number" id="first"><br>
                Input a number: <input class="form-control" type="number" id="second"><br>
                Input a number: <input class="form-control" type="number" id="third"><br>
                Input a number: <input class="form-control" type="number" id="fourth"><br>
                Input a number: <input class="form-control" type="number" id="fifth"><br><br>
            </form><br>
        </div>
    </div>*@
</div>

<div class="modal" id="max" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h1 class="modal-title" id="myModalLabel">Code for Problem 1</h1>
            </div>
            <div class="modal-body">
                <pre class="brush: js; gutter: false; toolbar: false;">

                    function min() {
		                var a = document.getElementById("first").value;
		                var b = document.getElementById("second").value;
		                var c = document.getElementById("third").value;
		                var d = document.getElementById("fourth").value;
		                var e = document.getElementById("fifth").value;
		                var least = Math.min(a, b, c, d, e);
		                temp1.innerHTML = "The least of the numbers is: " + least;
	                }
	
	                function max() {
		                var a = document.getElementById("first").value;
		                var b = document.getElementById("second").value;
		                var c = document.getElementById("third").value;
		                var d = document.getElementById("fourth").value;
		                var e = document.getElementById("fifth").value;
		                var least = Math.max(a, b, c, d, e);
                        temp2.innerHTML = "The least of the numbers is: " + least;
	                }
	
	                function mean() {
		                var a = document.getElementById("first").value;
		                var b = document.getElementById("second").value;
		                var c = document.getElementById("third").value;
		                var d = document.getElementById("fourth").value;
		                var e = document.getElementById("fifth").value;
		                var avg = (+a + +b + +c + +d + +e)/5;
		                window.alert("The mean of the numbers is: " + avg);
	                }
	                function add() {
		                var a = document.getElementById("first").value;
		                var b = document.getElementById("second").value;
		                var c = document.getElementById("third").value;
		                var d = document.getElementById("fourth").value;
		                var e = document.getElementById("fifth").value;
		                var avg = +a + +b + +c + +d + +e;
		                window.alert("The total sum of the numbers is: " + avg);
	                }
	                function mult() {
		                var a = document.getElementById("first").value;
		                var b = document.getElementById("second").value;
		                var c = document.getElementById("third").value;
		                var d = document.getElementById("fourth").value;
		                var e = document.getElementById("fifth").value;
		                var avg = +a * +b * +c * +d * +e;
		                window.alert("The product of the numbers is: " + avg);
	                }
                </pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
    
@section scripts{
<script>
    function min() {
	    var a = document.getElementById("first").value;
	    var b = document.getElementById("second").value;
	    var c = document.getElementById("third").value;
	    var d = document.getElementById("fourth").value;
	    var e = document.getElementById("fifth").value;
	    var least = Math.min(a, b, c, d, e);
	    temp1.innerHTML = least;
    }
	
    function max() {
	    var a = document.getElementById("first").value;
	    var b = document.getElementById("second").value;
	    var c = document.getElementById("third").value;
	    var d = document.getElementById("fourth").value;
	    var e = document.getElementById("fifth").value;
	    var great = Math.max(a, b, c, d, e);
	    temp2.innerHTML = great;
    }
	
    function mean() {
	    var a = document.getElementById("first").value;
	    var b = document.getElementById("second").value;
	    var c = document.getElementById("third").value;
	    var d = document.getElementById("fourth").value;
	    var e = document.getElementById("fifth").value;
	    var avg = (+a + +b + +c + +d + +e)/5;
	    temp3.innerHTML = avg;
    }

    function add() {
	    var a = document.getElementById("first").value;
	    var b = document.getElementById("second").value;
	    var c = document.getElementById("third").value;
	    var d = document.getElementById("fourth").value;
	    var e = document.getElementById("fifth").value;
	    var add = +a + +b + +c + +d + +e;
	    temp4.innerHTML = add;
    }

    function mult() {
	    var a = document.getElementById("first").value;
	    var b = document.getElementById("second").value;
	    var c = document.getElementById("third").value;
	    var d = document.getElementById("fourth").value;
	    var e = document.getElementById("fifth").value;
	    var mult = +a * +b * +c * +d * +e;
	    temp5.innerHTML = mult;
    }
</script>}

Galo_Personal_Site/Views/JavaScript/JSProblems.cshtml
<head>
    <title>JS Problems</title>
    <link href="Content/bootstrap.css" rel="stylesheet" />
    <link href="Content/shCoreDefault.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row"><br /></div>
        <div class="row">
            <div class="col-xs-4">
                <h1>JavaScript Exercises</h1>
            </div>
        </div>
        <div class="row">
            <br />
            <div class="col-xs-12">
                Following are some exercises which make use of JavaScript, jQuery, and CSS under the Bootstrap framework.<br /><br /><br />
                @Html.ActionLink("EX. 1", "Exeuno", "JavaScript", null, new { @class = "btn btn-warning" })<br /><br />
                @Html.ActionLink("EX. 2", "Exedos", "JavaScript", htmlAttributes: new { @class = "btn btn-primary" })<br /><br />
                @Html.ActionLink("EX. 3", "Exetres", "JavaScript", htmlAttributes: new { @class = "btn btn-success" })<br /><br />
                @Html.ActionLink("EX. 4", "Execuatro", "JavaScript", htmlAttributes: new { @class = "btn btn-info" })<br /><br />
                @Html.ActionLink("EX. 5", "Execinco", "JavaScript", htmlAttributes: new { @class = "btn btn-warning" })<br /><br />
            </div>
        </div>
    </div>
</body>